train :
  num_workers : 15

validate :
  num_workers : 15

data :
  nb_data : 50000
  train_data : 'two_defects'
  # select : all / low / nonbasis / pert / nocenter / magpert / mag / two_layer / two_defects
  eq_config :
    - 10
    - 20
    - 40
    - 5
  split_ratio :
    - 0.8
    - 0.2
  noise :
    - 0.05


net :
  loss : 'causal'
  hidden_layer : 
    - 1000
    - 1000
    - 1000
  nb_layer : 4

  dropout: False
  dropout_rate: 0
  batch: False
  weight_regularize: False
  weight_regularize_param: 0.1
  # select : observe / causal

